---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  KUBE_VIP_INTERFACE: "${BOOTSTRAP_KUBE_VIP_INTERFACE}"
  KUBE_VIP_ADDRESS: "${BOOTSTRAP_KUBE_VIP_ADDRESS}"
  KUBE_VIP_LB_RANGE: "${BOOTSTRAP_KUBE_VIP_LB_RANGE}"
  KUBE_VIP_TRAEFIK_ADDR: "${BOOTSTRAP_KUBE_VIP_TRAEFIK_ADDR}"
